import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import vm from 'node:vm';
import worker from '../worker/index.js';
import {client} from '../worker/ui.js';
import {database} from './d1-local.mjs';
new vm.Script(client);
const env={DB:database(),SYNC_TOKEN:'test-secret',OWNER_EMAIL:'owner@example.test'};
const origin='https://unit.example.chatgpt.site';
const digest=s=>createHash('sha256').update(s).digest('hex');
async function request(path,data,own=false,sync=false){const headers={};if(own)headers['oai-authenticated-user-email']=env.OWNER_EMAIL;if(sync)headers.Authorization='Bearer test-secret';if(data){headers['Content-Type']='application/json';headers.Origin=origin;}const response=await worker.fetch(new Request(origin+path,{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined}),env);return {status:response.status,data:await response.json()};}
const records=[['paper','doi:1',{identity:'doi:1',title:'Evidence paper',score:.8,eligibility_status:'eligible',abstract:'Original evidence',reasoning_json:'PRIVATE AUDIT REASONING',themes_json:'PRIVATE PERSONAL THEMES',score_dimensions_json:'PRIVATE AUDIT DIMENSIONS'}],['private','profile',{content:'Private personal profile'}],['feedback','doi:1',{identity:'doi:1',favorite:1,updated_at:'2026-01-01T00:00:00Z'}],['meta','overview',{threshold:.7,days:[],timezone:'Asia/Shanghai',sources:[],counts:{total:1}}]].map(([kind,key,value])=>{const data=JSON.stringify(value);return {kind,key,data,checksum:digest(data)};}).sort((a,b)=>a.kind.localeCompare(b.kind)||a.key.localeCompare(b.key));
const generation=digest(records.map(r=>`${r.kind}:${r.key}:${r.checksum}`).join('\n'));
assert.equal((await request('/api/sync/begin',{generation,count:records.length})).status,401);
assert.equal((await request('/api/sync/begin',{generation,count:records.length},false,true)).status,200);
assert.equal((await request('/api/sync/chunk',{generation,records:records.slice(0,1)},false,true)).status,200);
assert.equal((await request('/api/sync/finish',{generation},false,true)).status,409);
assert.equal((await request('/api/view?view=library')).status,503);
await request('/api/sync/chunk',{generation,records},false,true);
assert.equal((await request('/api/sync/finish',{generation},false,true)).status,200);
const publicView=await request('/api/view?view=library');assert.equal(publicView.status,200);assert.equal(publicView.data.papers.length,1);assert.equal(publicView.data.papers[0].feedback,undefined);assert.ok(!JSON.stringify(publicView).includes('Private personal profile'));
assert.ok(!JSON.stringify(publicView).includes('PRIVATE AUDIT'));assert.ok(!JSON.stringify(publicView).includes('PRIVATE PERSONAL THEMES'));
assert.equal((await request('/api/view?view=profile')).status,401);assert.equal((await request('/api/view?view=profile',null,true)).data.profile.content,'Private personal profile');
assert.equal((await request('/api/feedback',{identity:'doi:1',interest:null,favorite:0,reading_status:'read'})).status,401);
const patch={identity:'doi:1',interest:'interested',reason:'Specific decision mechanism',favorite:1,reading_status:'read'};
assert.equal((await request('/api/feedback',patch,true)).status,200);
const pulled=await request('/api/sync/feedback?after=0',null,false,true);assert.equal(pulled.data.events.length,1);assert.equal(pulled.data.events[0].reading_status,'read');assert.equal(pulled.data.cursor,1);
const broken='b'.repeat(64);await request('/api/sync/begin',{generation:broken,count:1},false,true);await request('/api/sync/chunk',{generation:broken,records:records.slice(0,1)},false,true);assert.equal((await request('/api/sync/finish',{generation:broken},false,true)).status,409);assert.equal((await request('/api/view?view=library')).data.generation,generation);
console.log('Worker verification passed: anonymous privacy, owner access, atomic snapshots, checksum refusal, feedback sync.');
// Reuse unchanged records; only a changed paper is uploaded before atomic activation.
const next=records.map(r=>r.kind==='paper'?(()=>{const p=JSON.parse(r.data);p.score=.6;const data=JSON.stringify(p);return {...r,data,checksum:digest(data)};})():r);
const nextGeneration=digest(next.map(r=>`${r.kind}:${r.key}:${r.checksum}`).join('\n'));
const opened=await request('/api/sync/begin',{generation:nextGeneration,count:next.length,manifest:next.map(({kind,key,checksum})=>({kind,key,checksum}))},false,true);
assert.equal(opened.status,200);assert.deepEqual(opened.data.missing,[{kind:'paper',key:'doi:1'}]);
assert.equal((await request('/api/view?view=library')).data.generation,generation);
await request('/api/sync/chunk',{generation:nextGeneration,records:next.filter(r=>r.kind==='paper')},false,true);
assert.equal((await request('/api/sync/finish',{generation:nextGeneration},false,true)).status,200);
assert.equal((await request('/api/view?view=library')).data.papers.length,0);
assert.equal((await request('/api/view?view=feedback',null,true)).data.papers.length,1);
const otherUser=await worker.fetch(new Request(origin+'/api/view?view=profile',{headers:{'oai-authenticated-user-email':'different@example.test'}}),env);
assert.equal(otherUser.status,401);
const csrf=await worker.fetch(new Request(origin+'/api/feedback',{method:'POST',headers:{'oai-authenticated-user-email':env.OWNER_EMAIL,'Content-Type':'application/json',Origin:'https://foreign.example'},body:JSON.stringify(patch)}),env);
assert.equal(csrf.status,403);
console.log('Incremental snapshots, downgraded-paper feedback, other-account privacy and CSRF verification passed.');
